// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    dailyLogs,
    dailyLogSymptoms,
    appSettings,
  ];
  late final Shape0 dailyLogs = Shape0(
    source: i0.VersionedTable(
      entityName: 'daily_logs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(date)',
        'CHECK((flow IS NULL)OR(is_period_day = 1))',
      ],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 dailyLogSymptoms = Shape1(
    source: i0.VersionedTable(
      entityName: 'daily_log_symptoms',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(log_date, symptom)',
        'FOREIGN KEY(log_date)REFERENCES daily_logs(date)ON DELETE CASCADE',
      ],
      columns: [_column_7, _column_8],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 appSettings = Shape2(
    source: i0.VersionedTable(
      entityName: 'app_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'CHECK(id = 0)'],
      columns: [
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get date =>
      columnsByName['date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isPeriodDay =>
      columnsByName['is_period_day']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get flow =>
      columnsByName['flow']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mood =>
      columnsByName['mood']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get periodDayExplicit =>
      columnsByName['period_day_explicit']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get periodEnd =>
      columnsByName['period_end']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'date',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_1(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_period_day',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_period_day IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'flow',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'mood',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'notes',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'period_day_explicit',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (period_day_explicit IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'period_end',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NULL CHECK (period_end IS NULL OR is_period_day = 1)',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get logDate =>
      columnsByName['log_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get symptom =>
      columnsByName['symptom']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'log_date',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'symptom',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get onboardingSeen =>
      columnsByName['onboarding_seen']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get notificationsEnabled =>
      columnsByName['notifications_enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get periodReminderEnabled =>
      columnsByName['period_reminder_enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fertileWindowRemindersEnabled =>
      columnsByName['fertile_window_reminders_enabled']!
          as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get showDetailsEnabled =>
      columnsByName['show_details_enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get reminderHour =>
      columnsByName['reminder_hour']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get reminderMinute =>
      columnsByName['reminder_minute']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get typicalPeriodLength =>
      columnsByName['typical_period_length']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'onboarding_seen',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (onboarding_seen IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'notifications_enabled',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (notifications_enabled IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'period_reminder_enabled',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 1 CHECK (period_reminder_enabled IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_13(
  String aliasedName,
) => i1.GeneratedColumn<int>(
  'fertile_window_reminders_enabled',
  aliasedName,
  false,
  type: i1.DriftSqlType.int,
  $customConstraints:
      'NOT NULL DEFAULT 0 CHECK (fertile_window_reminders_enabled IN (0, 1))',
  defaultValue: const i1.CustomExpression('0'),
);
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'show_details_enabled',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (show_details_enabled IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'reminder_hour',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 9',
      defaultValue: const i1.CustomExpression('9'),
    );
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'reminder_minute',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'typical_period_length',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 5 CHECK (typical_period_length BETWEEN 1 AND 15)',
      defaultValue: const i1.CustomExpression('5'),
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from3To4: from3To4),
);
